application: billkatz-test
version: 7-16-2009-1
runtime: python
api_version: 1

handlers:
- url: .*/favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: .*
  script: main.py

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (tests/.*)
 )$
